src/Entity/Ue.php
<?php

namespace App\Entity;

use App\Repository\UeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UeRepository::class)
 */
class Ue
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $Id_UE;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom_UE;

    /**
     * @ORM\Column(type="integer")
     */
    private $Etcs_UE;


    public function getIdUE(): ?int
    {
        return $this->Id_UE;
    }

    public function setIdUE(int $Id_UE): self
    {
        $this->Id_UE = $Id_UE;

        return $this;
    }

    public function getNomUE(): ?string
    {
        return $this->Nom_UE;
    }

    public function setNomUE(string $Nom_UE): self
    {
        $this->Nom_UE = $Nom_UE;

        return $this;
    }

    public function getEtcsUE(): ?int
    {
        return $this->Etcs_UE;
    }

    public function setEtcsUE(int $Etcs_UE): self
    {
        $this->Etcs_UE = $Etcs_UE;

        return $this;
    }
}

src/Controller/AjouterController.php
<?php


namespace App\Controller;


use App\Form\AjouterNotesType;
use App\Form\AjouterNotesUeType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Form\DonneesCapteurType;
use App\Entity\Vehicule;
use App\Entity\Infraction;
use App\Entity\Note;
use App\Entity\Etudiant;
use App\Entity\Usager;
use App\Entity\Sanction;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use App\Entity\Type;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class AjouterController extends AbstractController
{
    /**
     * @Route("/ajouternotes", name="ajouter_notes")
     */
    public function DonneesC(Request $req, EntityManagerInterface $em,AuthenticationUtils $authenticationUtils) {

        $entityManager = $this->getDoctrine()->getManager();
        $bool = false;
        $listEtudiant2 = $entityManager->getRepository('\App\Entity\Etudiant')->findAll();
        $listEtudiant =  array();
        foreach ($listEtudiant2 as $etudiant){
            $listEtudiant[$etudiant->getNomETUDIANT()." ".$etudiant->getPrenomETUDIANT()]= $etudiant->getId();

        }
        $listUe2 = $entityManager->getRepository('\App\Entity\Ue')->findAll();
        $listUe =  array();
        foreach ($listUe2 as $ue){
            $listUe[$ue->getNomUE()]= $ue->getIdUE();
        }

        $form = $this->createForm(AjouterNotesType::class, null, [
            'method' => 'POST',
            'action' => '/ajouternotes2',
            'listEtudiant'=>$listEtudiant,
            'listUe'=>$listUe,

        ]);

        $response = $this->render('ajouter/ajouter_notes.html.twig', [
            'formAjouterNotes' => $form->createView() ,'etudiants'=>$listEtudiant2,'ues'=>$listUe2, 'estInserer' => $bool,
        ]);

        return $response;
    }

    /**
     * @Route("ajouternotes2", name="create_noteAAAAAAAAAAAA")
     */
    public function AjoutDonneesC(Request $req, EntityManagerInterface $em) {
        //dump($req);
        $entityManager = $this->getDoctrine()->getManager();

        $listEtudiant2 = $entityManager->getRepository('\App\Entity\Etudiant')->findAll();
        $listEtudiant =  array();
        foreach ($listEtudiant2 as $etudiant){
            $listEtudiant[$etudiant->getNomETUDIANT()." ".$etudiant->getPrenomETUDIANT()]= $etudiant->getId();

        }
        $listUe2 = $entityManager->getRepository('\App\Entity\Ue')->findAll();
        $listUe =  array();
        foreach ($listUe2 as $ue){
            $listUe[$ue->getNomUE()]= $ue->getIdUE();
        }

        $form = $this->createForm(AjouterNotesType::class, null, [
            'method' => 'POST',
            'action' => '/ajouternotes2',
            'listEtudiant'=>$listEtudiant,
            'listUe'=>$listUe,

        ]);

        if ($req) {
            $dataNote = $req->request->get('ajouter_notes');
//           $idnote = $dataNote["idnote"];
            $note1 = $dataNote["note"];
            $coeffnote = $dataNote["coeffnote"];
            $idue = $dataNote["idue"];
            $idetudiant = $dataNote["idetudiant"];


//            $etudiant = $em->getRepository('\App\Entity\Etudiant')->find($dataNote["etudiant"]);
            $entityManager = $this->getDoctrine()->getManager();
            $note= new Note();
            //$note->setIdNOTE();
            $note->setNoteNOTE($note1);
            $note->setTestnoteNOTE($idetudiant);
            $note->setIdUE($idue);
            $note->setCoeffNOTE($coeffnote);

            // tell Doctrine you want to (eventually) save the Product (no queries yet)
            $entityManager->persist($note);

            // actually executes the queries (i.e. the INSERT query)
            $entityManager->flush();

            $entityManager = $this->getDoctrine()->getManager();
//    POURN FAIRE AVEC LISTE DEROULANTE$type = $entityManager->getRepository('\App\Entity\Type')->find($typeId);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($note);
            $entityManager->flush();

            $bool = true;
        } else {

            $bool = false;
        }

//        $response = $this->render('ajouter/ajouter_notes_message.html.twig', [
//            'estInserer' => $bool,
        $response = $this->render('ajouter/ajouter_notes.html.twig', [
            'formAjouterNotes' => $form->createView() ,'etudiants'=>$listEtudiant2,'ues'=>$listUe2 , 'estInserer' => $bool,
        ]);

        $this->addFlash('success','Article ajouté beau goss');
        return $response;
    }

    /**
     * @Route("/ajouternotesue/{id}", name="ajouter_notes_ue")
     */
    public function DonneesD(Request $req,$id, EntityManagerInterface $em,AuthenticationUtils $authenticationUtils) {
        $entityManager = $this->getDoctrine()->getManager();

        $ues = $em->getRepository('App:Ue')->findAll();
        $listeUe = array();
        $listEtudiant2 = $entityManager->getRepository('\App\Entity\Etudiant')->findAll();
        $listEtudiant =  array();

        $uesetus = $entityManager->getRepository('\App\Entity\LiaisonUeEtudiant')->findAll();
        $listeUeEtudiant =  array();

        $etudiants = $entityManager->getRepository('\App\Entity\Etudiant')->findAll();
        $compteEtudiant =  array();

        foreach ($uesetus as $ueetu) {
//            if ($ueetu->getIdUE() == $id) {
                array_push($listeUeEtudiant, $ueetu);
        }

        foreach ($listEtudiant2 as $etudiant){
            $listEtudiant[$etudiant->getNomETUDIANT()." ".$etudiant->getPrenomETUDIANT()]= $etudiant->getId();
        }

        foreach($etudiant as $etudiant) {
                array_push($compteEtudiant, $etudiant);
            }

        foreach($ues as $ue) {
            if ($ue->getIdUE() == $id) {
                array_push($listeUe, $ue);
            }
        }
        $form = $this->createForm(AjouterNotesUeType::class, null, [
            'method' => 'POST',
            'action' => '/ajouternotesUE',
            'listEtudiant'=>$listEtudiant,
        ]);
        $response = $this->render('ajouter/ajouter_notes_ue.html.twig', [
            'formAjouterNotes' => $form->createView() ,'etudiants'=>$listEtudiant2,'ues'=>$listeUe,'uesetus'=>$listeUeEtudiant
        ]);

        return $response;
    }
//Méthode de remplissage formulaire
    /**
     * @Route("ajouternotesUE", name="create_noteUE")
     */
    public function AjoutDonneesCUE(Request $req, EntityManagerInterface $em) {
        //dump($req);

//        $id=1;
        $uesetus = $em->getRepository('\App\Entity\LiaisonUeEtudiant')->findAll();
        $listeUeEtudiant =  array();

        $ue = $em->getRepository('\App\Entity\Ue')->findAll();
        $listeUeEtudiant =  array();

//        foreach ($uesetus as $ueetu) {
//            if ($ueetu->getIdUE() == $id) {
//                array_push($listeUeEtudiant, $ueetu);
//            }
//        }
//        $id=$uesetus->getIdUe();
        if ($req) {
            $dataNote = $req->request->get('ajouter_notes_ue');
//           $idnote = $dataNote["idnote"];
            $note1 = $dataNote["note"];
            $coeffnote = $dataNote["coeffnote"];
//            $idue = $dataNote["idue"];
            $idetudiant = $dataNote["idetudiant"];
            $idue = $ue->getIdUe();


//            $etudiant = $em->getRepository('\App\Entity\Etudiant')->find($dataNote["etudiant"]);
            $entityManager = $this->getDoctrine()->getManager();
            $note= new Note();
            //$note->setIdNOTE();
            $note->setNoteNOTE($note1);
            $note->setTestnoteNOTE($idetudiant);
            $note->setIdUE($idue);
            $note->setCoeffNOTE($coeffnote);

            // tell Doctrine you want to (eventually) save the Product (no queries yet)
            $entityManager->persist($note);

            // actually executes the queries (i.e. the INSERT query)
            $entityManager->flush();

            $entityManager = $this->getDoctrine()->getManager();
//    POURN FAIRE AVEC LISTE DEROULANTE$type = $entityManager->getRepository('\App\Entity\Type')->find($typeId);

            $entityManager = $this->getDoctrine()->getManager();

            // tell Doctrine you want to (eventually) save the Product (no queries yet)
            $entityManager->persist($note);

            // actually executes the queries (i.e. the INSERT query)
            $entityManager->flush();

            $bool = true;
        } else {

            $bool = false;
        }

        $response = $this->render('ajouter/ajouter_notes_message.html.twig', [
            'estInserer' => $bool,
        ]);

        return $response;
    }

    //Liste des UE
    /**
     * @Route("/ajouternoteslisteue", name="ajouter_notes_listeue")
     */
    public function ajouter_notes_listeue(EntityManagerInterface $em )
    {
        $ues = $em->getRepository('App:Ue')->findAll();
        $listeUe = array();

        foreach($ues as $ue){


            array_push($listeUe,$ue);

        }

        return $this->render('ajouter/ajouter_notes_listeue.html.twig',['ues'=>$listeUe]);
    }
}

templates/ajouter/ajouter_notes.html.twig
{% extends 'base.html.twig' %}

{% block title %}Enregister notes{% endblock %}

{% block contenu %}

    <div style="text-align: center;">
        {% if estInserer %}
            <p>Insertion réussie</p>
        {% else %}
            <p>Vous pouvez insérer des notes</p>
        {% endif %}

    </div>
    </br>
<div style=" display: flex; justify-content: flex-start">


    <div style="justify-content: flex-start; flex: auto; width:25%;height:600px;overflow:auto;">
        <table id="table_note"  class="table" >
            <thead class="thead-dark">
            <tr>
                <th scope="col">Nom UE</th>
                <th scope="col">ID</th>
                <th></th>
            </tr>
            </thead>

            {% for ue in ues %}
                <tr>
                    <th> <h >{{ ue.NomUE}}</h> </th>
                    <th><h font-color="red">{{ ue.IdUE}}</h> </th>
                </tr>

            {% endfor %}
        </table>
    </div>


{#    <div style="text-align: center;">#}
{#        <h2>Ajouter Note</h2>#}
{#    </div>#}
    <div style=" flex: auto; text-align: center;position: sticky; position: -webkit-sticky;top: 20px"> {#style="margin-top: 5%;margin-left: 25%;margin-right: 25%;text-align: center;">#}
        <!-- Capteur Formulaire -->
        {% form_theme formAjouterNotes'bootstrap_4_layout.html.twig' %}

        {{ form_start(formAjouterNotes) }}
{#        {{ form_widget(formAjouterNotes.idnote) }}#}
        {{ form_widget(formAjouterNotes.note) }}
        {{ form_widget(formAjouterNotes.coeffnote) }}
        {{ form_widget(formAjouterNotes.idue) }}
        {{ form_widget(formAjouterNotes.idetudiant) }}


{#        {{ form_row(formAjouterNotes.etudiant) }}#}
{#        {{ form_row(formAjouterNotes.ue) }}#}
        <br>
        <br>
        {{ form_widget(formAjouterNotes.enregistrer) }}

        {{ form_end(formAjouterNotes) }}
    </div>
    <div style="justify-content: flex-start; flex: auto; width:25%;height:600px;overflow:auto;">
        <table id="table_note"  class="table" >
            <thead class="thead-dark">
            <tr>
                <th scope="col">Nom</th>
                <th scope="col">Prénom</th>
                <th scope="col">ID</th>
                <th></th>
            </tr>
            </thead>

            {% for etudiant in etudiants %}
                <tr>
                    <th> <h >{{ etudiant.NomETUDIANT}}</h> </th>
                    <th><h ></h>{{ etudiant.PrenomETUDIANT}} </th>
                    <th><h font-color="red">{{ etudiant.IdETUDIANT}}</h> </th>
                </tr>

            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

templates/ajouter/ajouter_notes_listeue.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des UE {% endblock %}

{% block contenu %}
    {% for ue in ues %}
    <div style="text-align: center;">
        <tr>
            <th><a class="btn btn-warning" role="button" href="{{ path('ajouter_notes_ue',{'id':ue.idUE}) }}"><h4>{{ ue.NomUE}}</h4></a></th>
        </tr>
        <div class="col-md-auto">

        </div>
        {% endfor %}
    </div>

{% endblock %}

templates/ajouter/ajouter_notes_message.html.twig
{% extends 'base.html.twig' %}

{% block title %}Enregister capteur{% endblock %}

{% block contenu %}

    <div style="text-align: center;">
        <p>Enregistrer informations d'un capteur </p>
    </div>
    <div style="text-align: center;">
        {% if estInserer %}
            <p>Insersion réussie</p>
        {% else %}
            <p>Erreur insersion</p>
        {% endif %}

    </div>

{% endblock %}

templates/ajouter/ajouter_notes_ue.html.twig
{% extends 'base.html.twig' %}

{% block title %}Enregister Notes par Ue{% endblock %}

{% block contenu %}
    </br>
    <div>
        <h1 id="header2"> {% for ue in ues %}
                <tr>
                    <th> <h >{{ ue.NomUE}}</h> </th>
                </tr>


            {% endfor %}</h1>
    </div>
    <div style=" display: flex; justify-content: flex-start">




{#        <div style="justify-content: flex-start; flex: auto; width:25%;height:600px;overflow:auto;">#}
{#qsdsqdqs#}
{#        </div>#}
        {#    <div style="text-align: center;">#}
        {#        <h2>Ajouter Note</h2>#}
        {#    </div>#}
        <div style=" flex: auto; text-align: center;position: sticky; position: -webkit-sticky;top: 20px"> {#style="margin-top: 5%;margin-left: 25%;margin-right: 25%;text-align: center;">#}
            <!-- Capteur Formulaire -->
            {% for ue in ues %}
            {% form_theme formAjouterNotes'bootstrap_4_layout.html.twig' %}

                <div class="form-group">
                    <label>IdUE</label>
                    <p type="password" class="form-control">{{ ue.idue}}</p>
                </div>
            {{ form_start(formAjouterNotes) }}
            {{ form_widget(formAjouterNotes.note) }}
            {{ form_widget(formAjouterNotes.coeffnote) }}
            {{ form_widget(formAjouterNotes.idetudiant) }}

            <br>
            <br>
                {% set id=2 %}
            {{ form_widget(formAjouterNotes.enregistrer ) }}

            {{ form_end(formAjouterNotes) }}
            {% endfor %}
        </div>

        <div style="justify-content: flex-start; flex: auto; width:25%;height:600px;overflow:auto;">
            <table id="table_note"  class="table" >
                <thead class="thead-dark">
                <tr>
                    <th scope="col">Nom</th>
                    <th scope="col">Prénom</th>
                    <th scope="col">ID</th>
                    <th></th>
                </tr>
                </thead>

                {% for etudiant in etudiants %}
                    <tr>
                        <th> <h >{{ etudiant.NomETUDIANT}}</h> </th>
                        <th><h ></h>{{ etudiant.PrenomETUDIANT}} </th>
                        <th><h >{{ etudiant.IdETUDIANT}}</h> </th>
                        <th><h >
                        </h> </th>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}