src/Entity/Etudiant.php
<?php

namespace App\Entity;

use App\Repository\EtudiantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=EtudiantRepository::class)
 */
class Etudiant
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $Id_ETUDIANT;

    public function __toString()
    {
        return (string) $this->Id_ETUDIANT;
    }



    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom_ETUDIANT;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom_ETUDIANT;

    /**
     * @ORM\OneToMany(targetEntity=Note::class, mappedBy="Id_ETUDIANT")
     */
    private $Note_ETUDIANT;

//    /**
//     * @ORM\Column(type="integer")
//     */
//    private $Id_ETUDIANT;

    public function __construct()
    {
        $this->Note_ETUDIANT = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->Id_ETUDIANT;
    }


    public function getPrenomETUDIANT(): ?string
    {
        return $this->Prenom_ETUDIANT;
    }

    public function setPrenomETUDIANT(string $Prenom_ETUDIANT): self
    {
        $this->Prenom_ETUDIANT = $Prenom_ETUDIANT;

        return $this;
    }

    public function getNomETUDIANT(): ?string
    {
        return $this->Nom_ETUDIANT;
    }

    public function setNomETUDIANT(string $Nom_ETUDIANT): self
    {
        $this->Nom_ETUDIANT = $Nom_ETUDIANT;

        return $this;
    }

    /**
     * @return Collection|Note[]
     */
    public function getNoteETUDIANT(): Collection
    {
        return $this->Note_ETUDIANT;
    }

    public function addNoteETUDIANT(Note $noteETUDIANT): self
    {
        if (!$this->Note_ETUDIANT->contains($noteETUDIANT)) {
            $this->Note_ETUDIANT[] = $noteETUDIANT;
            $noteETUDIANT->setIdETUDIANT($this);
        }

        return $this;
    }

    public function removeNoteETUDIANT(Note $noteETUDIANT): self
    {
        if ($this->Note_ETUDIANT->removeElement($noteETUDIANT)) {
            // set the owning side to null (unless already changed)
            if ($noteETUDIANT->getIdETUDIANT() === $this) {
                $noteETUDIANT->setIdETUDIANT(null);
            }
        }

        return $this;
    }

    public function getIdETUDIANT(): ?int
    {
        return $this->Id_ETUDIANT;
    }

    public function setIdETUDIANT(int $Id_ETUDIANT): self
    {
        $this->Id_ETUDIANT = $Id_ETUDIANT;

        return $this;
    }

}

src/Controller/GestionCompteController.php
<?php

namespace App\Controller;

use App\Form\GetLinkForRestType;
use App\Form\ResetPasswordType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class GestionCompteController extends AbstractController
{

    /**
     * @return Response
     * @Route("/gestion/compte",
     * name="gestion_compte")
     */
    public function gestionCompte()
    {
        return $this->render('gestion_compte/gestionCompte.html.twig');
    }



    /**
     * @param EntityManagerInterface $em
     * @return Response
     * @Route("/gestion/compte/admin",
     * name="gestion_compteAdmin")
     */
    /**
     * @param EntityManagerInterface $em
     * @return Response
     * @Route("/gestion/compte/admin",
     * name="gestion_compteAdmin")
     */
    public function gestionCompteAdmin(EntityManagerInterface $em)
    {
        $comptes = $em->getRepository('App:UtilisateurSite')->findAll();
        $compteAdmin = array();

        foreach($comptes as $compte){
            if($compte->getRole() == "admin" && $compte->getIsDesactivate() == false){
                array_push($compteAdmin,$compte);
            }
        }

        return $this->render('gestion_compte/compte.html.twig',['comptes'=>$compteAdmin]);
    }


    /**
     * @param EntityManagerInterface $em
     * @return Response
     * @Route("/gestion/compte/mention",
     * name="gestion_compteMention")
     */
    public function gestionCompteMention(EntityManagerInterface $em)
    {
        $comptes = $em->getRepository('App:UtilisateurSite')->findAll();
        $compteOpj = array();

        foreach($comptes as $compte){

            if($compte->getRole() == "mention" && $compte->getIsDesactivate() == false){
                array_push($compteOpj,$compte);
            }
        }

        return $this->render('gestion_compte/compte.html.twig',['comptes'=>$compteOpj]);
    }
    /**
     * @param EntityManagerInterface $em
     * @return Response
     * @Route("/gestion/compte/parcours",
     * name="gestion_compteParcours")
     */
    public function gestionCompteParcours(EntityManagerInterface $em)
    {
        $comptes = $em->getRepository('App:UtilisateurSite')->findAll();
        $compteUser = array();

        foreach($comptes as $compte){

            if($compte->getRole() == "parcours" && $compte->getIsDesactivate() == false){
                array_push($compteUser,$compte);
            }
        }

        return $this->render('gestion_compte/compte.html.twig',['comptes'=>$compteUser]);
    }
    /**
     * @param EntityManagerInterface $em
     * @return Response
     * @Route("/gestion/compte/Responsabledannee",
     * name="gestion_compteRannee")
     */
    public function gestionCompteRannee(EntityManagerInterface $em)
    {
        $comptes = $em->getRepository('App:UtilisateurSite')->findAll();
        $compteOpj = array();

        foreach($comptes as $compte){

            if($compte->getRole() == "rannee" && $compte->getIsDesactivate() == false){
                array_push($compteOpj,$compte);
            }
        }

        return $this->render('gestion_compte/compte.html.twig',['comptes'=>$compteOpj]);
    }
    /**
     * @param EntityManagerInterface $em
     * @return Response
     * @Route("/gestion/compte/enseignantdannee",
     * name="gestion_compteEannee")
     */
    public function gestionCompteEannee(EntityManagerInterface $em)
    {
        $comptes = $em->getRepository('App:UtilisateurSite')->findAll();
        $compteOpj = array();

        foreach($comptes as $compte){

            if($compte->getRole() == "eannee" && $compte->getIsDesactivate() == false){
                array_push($compteOpj,$compte);
            }
        }

        return $this->render('gestion_compte/compte.html.twig',['comptes'=>$compteOpj]);
    }
    /**
     * @param EntityManagerInterface $em
     * @return Response
     * @Route("/gestion/compte/ue",
     * name="gestion_compteUe")
     */
    public function gestionCompteUe(EntityManagerInterface $em)
    {
        $comptes = $em->getRepository('App:UtilisateurSite')->findAll();
        $compteOpj = array();

        foreach($comptes as $compte){

            if($compte->getRole() == "ue" && $compte->getIsDesactivate() == false){
                array_push($compteOpj,$compte);
            }
        }

        return $this->render('gestion_compte/compte.html.twig',['comptes'=>$compteOpj]);
    }


    /**
     * @param EntityManagerInterface $em
     * @return Response
     * @Route("/gestion/compte/desactive",
     * name="gestion_compteDesac")
     */
    public function gestionCompteDesactivate(EntityManagerInterface $em)
    {
        $comptes = $em->getRepository('App:UtilisateurSite')->findAll();
        $compteDesac = array();

        foreach($comptes as $compte){

            if($compte->getIsDesactivate() == true){
                array_push($compteDesac,$compte);
            }
        }

        return $this->render('gestion_compte/compte.html.twig',['comptes'=>$compteDesac]);
    }

    /**
     * @Route("/gestion/compte/desactive/{id}", name="deleteCompte")
     */
    public function desactivateCompte(EntityManagerInterface $em, $id){

        $compte = $em->getRepository('App:UtilisateurSite')->find($id);

        if(!$compte){
            throw new NotFoundHttpException("Le compte n'existe pas");
        }

        $compte->setIsDesactivate(true);
        $em->flush();

        return $this->redirectToRoute('gestion_compte');

    }

    /**
     * @Route("/gestion/compte/reactivate/{id}", name="reactivateCompte")
     */
    public function reactivateCompte(EntityManagerInterface $em, $id){

        $compte = $em->getRepository('App:UtilisateurSite')->find($id);

        if(!$compte){
            throw new NotFoundHttpException("Le compte n'existe pas");
        }

        $compte->setIsDesactivate(false);
        $em->flush();

        return $this->redirectToRoute('gestion_compte');

    }

    /**
     * @Route("/oubli", name="oublie")
     */
    public function forgotPassword(EntityManagerInterface $em,Request $req,\Swift_Mailer $mailer)
    {
        $form = $this->createForm(GetLinkForRestType::class);

        $form->handleRequest($req);

        if ($form->isSubmitted() && $form->isValid()) {

            $dataUti = $req->request->get('get_link_for_rest');
            $uti = $em->getRepository('App:UtilisateurSite')->findByLogin($dataUti["login"]);
            $lien = base64_encode($uti->getLogin());
            $message = (new \Swift_Message('Récupération de compte'))
                ->setFrom('pvnovacompte@gmail.com')
                ->setTo($dataUti["login"])
                ->setBody(
                    $this->renderView(
                        'gestion_compte/forgotPassword.html.twig',
                        ["lien" => $lien]
                    ),
                    'text/html'
                );
            $mailer->send($message);
            return $this->redirectToRoute('accueil');

        } else {
            return $this->render(
                'gestion_compte/getLinkForReset.html.twig',
                ["form" => $form->createView()]
            );
        }

    }

    /**
     * @Route("/reset/{login}", name="reset")
     */
    public function resetPassword(UserPasswordEncoderInterface $encode,EntityManagerInterface $em,Request $req,$login)
    {
        $uti = $em->getRepository('App:UtilisateurSite')->findByLogin(base64_decode($login));
        $form = $this->createForm(ResetPasswordType::class);
        $form->add('reset', SubmitType::class, array('label' => 'Réinitialiser'));

        $form->handleRequest($req);

        if ($form->isSubmitted() && $form->isValid()) {

            $dataUti = $req->request->get('reset_password');
            $encoded = $encode->encodePassword($uti, $dataUti["password"]["first"]);
            $uti->setPassword($encoded);
            $em->persist($uti);
            $em->flush();
            return $this->redirectToRoute('login');

        } else {
            return $this->render(
                'gestion_compte/getLinkForReset.html.twig',
                ["form" => $form->createView()]
            );
        }

    }
}

templates/gestion_compte/compte.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des comptes{% endblock %}

{% block contenu %}
    </br>

    <div>
        <a class="btn btn-secondary" role="button" href="{{ path('gestion_compte') }}">Retour</a>
    </div>

    </br>
    {% for compte in comptes %}
        <div class="modal fade" id="desac{{compte.id}}" tabindex="-1" role="dialog" aria-labelledby="refus" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle" style="color: red">Attention</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>

                        </button>
                    </div>
                    <div class="modal-body" style="text-align: center;">
                        <h1 id="question">Etes vous sûres de désactiver?</h1>
                        <a class="btn btn-success" role="button" href="{{ path('deleteCompte',{'id':compte.id}) }}">Oui</a>
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Non</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="d-flex w-100 justify-content-between">
                    <div class="col">
                        <h5 class="mb-1">{{ compte.login }}</h5>
                    </div>
                    {% if  compte.isDesactivate == false %}
{#                    <div class="col-md-auto">#}
{#                        <a class="btn btn-success" role="button" href="{{ path('modifCompte', {'id':compte.id}) }}">Modifier</a>#}
{#                    </div>#}
                    <div class="col-md-auto">
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#desac{{compte.id}}">Désactiver</button>
                    </div>
                    {% endif %}
                    {% if compte.isDesactivate == true %}
                        <div class="col-md-auto">
                            <a class="btn btn-warning" role="button" href="{{ path('reactivateCompte', {'id':compte.id}) }}">Réactiver</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        </br>
    {% endfor %}


{% endblock %}

templates/gestion_compte/forgotPassword.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Réinitialisé mot de passe</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link href="{{ asset('css/sidebar.css') }}" type="text/css" rel="stylesheet">

        <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <link rel="stylesheet" type="text/css" href="/css/style.css"/>

</head>
<body>
<header class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-3">
                <h1 class="text-uppercase">PV Nova</h1>
            </div>
            <div class="col-8">
                <h2>Agence nationale de traitement automatisé des infractions</h2>
            </div>
        </div>
    </div>
</header>
<main class="container-fluid" style="background-color: #0b6ba8; height: 100%;">
    <div class="container">
        <h3>Réinitialisé mot de passe : 127.0.0.1:8000/reset/{{ lien }}</h3>
    </div>
</main>
</body>
</html>

templates/gestion_compte/gestionCompte.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des comptes{% endblock %}

{% block contenu %}
    </br>
    {% if app.user %}
    {% if app.user.role == "admin" %}
    <div class="card">
        <div class="card-body">
            <div class="d-flex w-100 justify-content-between">
                <div class="col">
                    <h5 class="mb-1">Comptes Admin</h5>
                </div>
                <div class="col-md-auto">
                    <a class="btn btn-primary" role="button" href="{{ path('gestion_compteAdmin') }}">Visualiser</a>
                    <a class="btn btn-success" role="button" href="{{ path('crea_compteAdmin') }}">+</a>
                </div>
            </div>
        </div>
    </div>
{% if  app.user.role=="admin"%}
    </br>
    <div class="card">
        <div class="card-body">
            <div class="d-flex w-100 justify-content-between">
                <div class="col">
                    <h5 class="mb-1">Comptes Responsable de Mention </h5>
                </div>
                <div class="col-md-auto">
                    <a class="btn btn-primary" role="button" href="{{ path('gestion_compteMention') }}">Visualiser</a>
                    <a class="btn btn-success" role="button" href="{{ path('crea_compteMention') }}">+</a>
                </div>
            </div>
        </div>
    </div>
{% if app.user.role == "mention" or app.user.role=="admin"%}
    </br>
    <div class="card">
        <div class="card-body">
            <div class="d-flex w-100 justify-content-between">
                <div class="col">
                    <h5 class="mb-1">Comptes Responsable de Parcours </h5>
                </div>
                <div class="col-md-auto">
                    <a class="btn btn-primary" role="button" href="{{ path('gestion_compteParcours') }}">Visualiser</a>
                    <a class="btn btn-success" role="button" href="{{ path('crea_compteParcours') }}">+</a>
                </div>
            </div>
        </div>
    </div>
{% if app.user.role == "mention" or app.user.role=="admin" or app.user.role=="parcours" or app.user.role=="Rannee"%}
    </br>
    <div class="card">
        <div class="card-body">
            <div class="d-flex w-100 justify-content-between">
                <div class="col">
                    <h5 class="mb-1">Comptes Responsable d'année </h5>
                </div>
                <div class="col-md-auto">
                    <a class="btn btn-primary" role="button" href="{{ path('gestion_compteRannee') }}">Visualiser</a>
                    <a class="btn btn-success" role="button" href="{{ path('crea_compteRannee') }}">+</a>
                </div>
            </div>
        </div>
    </div>
    {% if app.user.role == "mention" or app.user.role=="admin" or app.user.role=="parcours" or app.user.role=="Rannee"%}
    </br>
    <div class="card">
        <div class="card-body">
            <div class="d-flex w-100 justify-content-between">
                <div class="col">
                    <h5 class="mb-1">Comptes D'enseignants d'année </h5>
                </div>
                <div class="col-md-auto">
                    <a class="btn btn-primary" role="button" href="{{ path('gestion_compteEannee') }}">Visualiser</a>
                    <a class="btn btn-success" role="button" href="{{ path('crea_compteEannee') }}">+</a>
                </div>
            </div>
        </div>
    </div>
{% if app.user.role == "mention" or app.user.role=="admin" or app.user.role=="parcours" or app.user.role=="Rannee"%}
    </br>
    <div class="card">
        <div class="card-body">
            <div class="d-flex w-100 justify-content-between">
                <div class="col">
                    <h5 class="mb-1">Comptes Responsable UE</h5>
                </div>
                <div class="col-md-auto">
                    <a class="btn btn-primary" role="button" href="{{ path('gestion_compteUe') }}">Visualiser</a>
                    <a class="btn btn-success" role="button" href="{{ path('crea_compteUe') }}">+</a>
                </div>
            </div>
        </div>
    </div>
{% if app.user.role == "mention" or app.user.role=="admin"%}
    </br>
    <div class="card">
        <div class="card-body">
            <div class="d-flex w-100 justify-content-between">
                <div class="col">
                    <h5 class="mb-1">Comptes Désactivé</h5>
                </div>
                <div class="col-md-auto">
                    <a class="btn btn-primary" role="button" href="{{ path('gestion_compteDesac') }}">Visualiser</a>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
{% endif %}
{% endif %}
{% endif %}
{% endif %}
{% endif %}
{% endif %}
{% endif %}
{% endblock %}

templates/gestion_compte/getLinkForReset.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mot de passe oublié{% endblock %}

{% block contenu %}

    {% form_theme form 'bootstrap_4_layout.html.twig' %}
    <h1>Mot de passe oublié</h1>

    {{ form_start(form) }}

    {{ form_end(form) }}
{% endblock %}

templates/gestion_compte/viewtest.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Etudiants{% endblock %}

{% block contenu %}

    <div>
        <a class="btn btn-secondary" role="button" href="{{ path('retour1') }}">Retour</a>
    </div>
    <div>
        <h1 id="header2">Liste Etudiants</h1>
    </div>

<div id="div_note">
    <table id="table_note"  class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">Nom</th>
            <th scope="col">Prenom</th>
            <th scope="col">Id</th>
            <th></th>
        </tr>
        </thead>
</div>
    {% for compte in comptes %}
        <div class="modal fade" id="desac{{compte.IdETUDIANT}}" tabindex="-1" role="dialog" aria-labelledby="refus" aria-hidden="true">
        </div>

{#                        //<h5 class="mb-1">{{ compte.id }} {{ compte.PrenomETUDIANT }}</h5>#}

                                <tr>
                                    <th> <h id="titre1">{{ compte.NomETUDIANT}}</h> </th>
                                    <th><h id="titre1"></h>{{ compte.PrenomETUDIANT}} </th>
                                    <th><h id="titre1">{{ compte.IdETUDIANT}}</h> </th>
                                    <th><a class="btn btn-warning" role="button" href="{{ path('profiletu', {'id':compte.idETUDIANT}) }}">Voir les Notes</a></th>
                                </tr>



                        <div class="col-md-auto">

                        </div>
                </div>
            </div>
            </div>
    {% endfor %}
    </table>


{% endblock %}

templates/gestion_compte/viewtetst.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des comptes{% endblock %}

{% block contenu %}
    </br>

    <div>
        <a class="btn btn-secondary" role="button" href="{{ path('gestion_compte') }}">Retour</a>
    </div>

    </br>
    {% for compte in comptes %}
        <div class="modal fade" id="desac{{compte.id}}" tabindex="-1" role="dialog" aria-labelledby="refus" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle" style="color: red">Attention</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>

                        </button>
                    </div>
                    <div class="modal-body" style="text-align: center;">
                        <h1 id="question">Etes vous sûres de désactiver?</h1>
                        <a class="btn btn-success" role="button" href="{{ path('deleteCompte',{'id':compte.id}) }}">Oui</a>
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Non</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="d-flex w-100 justify-content-between">
                    <div class="col">
                        <h5 class="mb-1">{{ compte.id }}</h5>
                    </div>
                    {% if compte.role == "opj" and compte.isDesactivate == false %}
                        <div class="col-md-auto">
                            <a class="btn btn-success" role="button" href="{{ path('modifCompte', {'id':compte.id}) }}">Modifier</a>
                        </div>
                        <div class="col-md-auto">
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#desac{{compte.id}}">Désactiver</button>
                        </div>
                    {% endif %}
                    {% if compte.isDesactivate == true %}
                        <div class="col-md-auto">
                            <a class="btn btn-warning" role="button" href="{{ path('reactivateCompte', {'id':compte.id}) }}">Réactiver</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        </br>
    {% endfor %}


{% endblock %}